import os

replacements = {
    "Экран камеры WayFinder. Нажмите центральную кнопку, чтобы проанализировать окружение. ": "WayFinder Camera Screen. Tap the central button to analyze surroundings. ",
    "Нажмите на микрофон слева, чтобы задать вопрос, или скажите: Way Finder.": "Tap the mic on the left to ask a question, or say: Way Finder.",
    "Анализирую, двигайтесь осторожно.": "Analyzing, move carefully.",
    "Высокая задержка сети. Анализирую, двигайтесь осторожно.": "High network latency. Analyzing, move carefully.",
    "Камера не найдена на этом устройстве.": "Camera not found on this device.",
    "Камера недоступна.": "Camera unavailable.",
    "Доступ к камере запрещен. Пожалуйста, откройте настройки и разрешите доступ для WayFinder.": "Camera access denied. Please open settings and allow access for WayFinder.",
    "Доступ к камере запрещен. Откройте настройки устройства.": "Camera access denied. Open device settings.",
    "Не удалось запустить камеру. Попробуйте еще раз.": "Failed to start camera. Please try again.",
    "Ошибка камеры. Нажмите кнопку повтора.": "Camera error. Tap retry button.",
    "Не удалось запустить камеру.": "Failed to start camera.",
    "Записываю окружение. Пожалуйста, подождите.": "Recording surroundings. Please wait.",
    "Анализирую...": "Analyzing...",
    "Анализирую окружение...": "Analyzing surroundings...",
    "Анализ окружения": "Analyze Surroundings",
    "Обработка...": "Processing...",
    "Произошла ошибка. Попробуйте еще раз.": "An error occurred. Please try again.",
    "Ошибка камеры. Пожалуйста, попробуйте еще раз.": "Camera error. Please try again.",
    "Камера недоступна. Нажмите дважды, чтобы повторить.": "Camera unavailable. Double tap to retry.",
    "Камера загружается": "Camera loading",
    "Инициализация камеры...": "Initializing camera...",
    "Повторить": "Repeat",
    "Статус приложения:": "App Status:",
    "Включен": "Enabled",
    "Выключен": "Disabled",
    "Вкл": "On",
    "Выкл": "Off",
    "Статус системы": "System Status",
    "Проверить состояние серверов и AI": "Check server and AI status",
    "Настройки": "Settings",
    "Открыть настройки профиля": "Open profile settings",
    "Готов": "Ready",
    "Слушаю...": "Listening...",
    "Говорю...": "Speaking...",
    "Ошибка": "Error",
    "Оффлайн": "Offline",
    "Указания по навигации:": "Navigation guidance:",
    "Уверенность:": "Confidence:",
    "Спросить WayFinder": "Ask WayFinder",
    "Задать вопрос голосом": "Ask a question with voice",
    "Проанализировать окружение": "Analyze Surroundings",
    "Навигация активна. Пожалуйста, подождите.": "Navigation active. Please wait.",
    "Получить описание окружения и препятствий": "Get description of surroundings and obstacles",
    "Анализ...": "Analysis...",
    "Остановить речь": "Stop Speaking",
    "Остановить аудио": "Stop Audio",
    "Немедленно прервать текущее голосовое сообщение": "Immediately interrupt current voice message",
    "Прервать текущее воспроизведение речи": "Interrupt current speech playback",
    "Прервать текущее воспроизведение ответа": "Interrupt current response playback",
    "Остановить": "Stop",
    "Повторить последнее сообщение": "Repeat last message",
    "Нет сообщений для повтора.": "No messages to repeat.",
    "Ассистент открыт. Нажмите на микрофон, чтобы задать вопрос о том, что вы видите.": "Assistant opened. Tap the mic to ask a question about what you see.",
    "Распознавание голоса недоступно на этом устройстве. Вы можете ввести свой вопрос текстом.": "Speech recognition unavailable on this device. You can type your question.",
    "Введите ваш вопрос.": "Type your question.",
    "Слушаю. Произнесите ваш вопрос сейчас.": "Listening. Speak your question now.",
    "Не удалось запустить распознавание голоса. Попробуйте ввести текст.": "Failed to start speech recognition. Please type your text.",
    "Прослушивание отменено.": "Listening cancelled.",
    "Я ничего не услышал. Нажмите на микрофон, чтобы попробовать еще раз.": "I didn't hear anything. Tap the mic to try again.",
    "Понял. Обрабатываю ваш вопрос.": "Got it. Processing your question.",
    "Ошибка распознавания голоса. Нажмите на микрофон, чтобы попробовать еще раз.": "Speech recognition error. Tap the mic to try again.",
    "Спросите о том, что видите": "Ask about what you see",
    "Нажмите на микрофон и произнесите свой вопрос.\\nНапример: \"Что находится передо мной?\"": "Tap the mic and speak your question.\\nExample: \"What is in front of me?\"",
    "Распознавание голоса недоступно.\\nВведите ваш вопрос ниже.": "Speech recognition unavailable.\\nType your question below.",
    "Ваш вопрос:": "Your question:",
    "Думаю...": "Thinking...",
    "Ответ:": "Answer:",
    "Повторить ответ": "Repeat answer",
    "Задать другой вопрос": "Ask another question",
    "Спросить снова": "Ask again",
    "Введите ваш вопрос": "Type your question",
    "Введите ваш вопрос...": "Type your question...",
    "Отправить вопрос": "Send Question",
    "Отменить запись": "Cancel recording",
    "Отменить прослушивание": "Cancel listening",
    "Закрыть ассистент": "Close assistant",
    "Закрыть ассистента": "Close assistant",
    "Нажмите, чтобы остановить прослушивание и отправить вопрос": "Tap to stop listening and send question",
    "Остановить запись и отправить вопрос": "Stop recording and send question",
    "Нажмите, чтобы задать вопрос голосом": "Tap to ask a question with voice",
    "Начать диктовку вопроса": "Start dictating question",
    "Пожалуйста, подождите, идет обработка вопроса": "Please wait, question is processing",
    "Пожалуйста, подождите, идет обработка": "Please wait, processing",
    "Отмена": "Cancel",
    "Закрыть": "Close",
    "Используйте большую кнопку Анализ окружения на главном экране, чтобы получить описание сцены перед вами.": "Use the large Analyze Surroundings button on the main screen to get a scene description.",
    "WayFinder видит за вас": "WayFinder sees for you",
    "Задавайте вопросы": "Ask Questions",
    "Используйте большую кнопку Спросить WayFinder, чтобы задавать вопросы голосом. Wake word (фраза Way Finder) опционален.": "Use the large Ask WayFinder button to ask questions with voice. Wake word (Way Finder) is optional.",
    "Контроль над речью": "Speech Control",
    "Используйте кнопку Остановить в любой момент, чтобы прервать аудио. Кнопка Повторить озвучит последнюю фразу заново.": "Use the Stop button at any time to interrupt audio. The Repeat button will read the last phrase again.",
    "Безопасная навигация": "Safe Navigation",
    "WayFinder сообщает о препятствиях. Помните, приложение является лишь помощником, будьте внимательны при движении.": "WayFinder reports obstacles. Remember, the app is only an assistant, be careful when moving.",
    "Пропустить введение": "Skip introduction",
    "Пропустить": "Skip",
    "Далее": "Next",
    "Начать": "Get Started",
    "довер.": "conf.",
    "довер": "conf",
}

files_to_check = [
    "mobile/lib/screens/home_camera_screen.dart",
    "mobile/lib/screens/ask_assistant_sheet.dart",
    "mobile/lib/screens/onboarding_screen.dart",
    "mobile/lib/core/accessibility.dart"
]

for filepath in files_to_check:
    full_path = os.path.join("/home/erbol/Рабочий стол/WayFinder/wayfinder2", filepath)
    if not os.path.exists(full_path):
        print(f"Skipping {full_path}, does not exist")
        continue
    with open(full_path, "r", encoding="utf-8") as f:
        content = f.read()
    
    for ru, en in replacements.items():
        content = content.replace(ru, en)
        
    with open(full_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Processed {filepath}")
