# Generated by Django 5.1.4 on 2026-03-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_uid', models.CharField(db_index=True, max_length=128)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('confidence', models.FloatField(default=0.0)),
                ('grounded', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, default='', max_length=32)),
                ('interaction_type', models.CharField(default='ask', max_length=16)),
                ('inference_ms', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['firebase_uid', '-created_at'], name='api_assista_firebas_24e338_idx')],
            },
        ),
    ]
