# Generated by Django 5.1.4 on 2026-05-07 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usersession_message'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='api_message_firebas_827794_idx',
            old_name='api_message_firebas_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='api_message_session_bbccd7_idx',
            old_name='api_message_session_idx',
        ),
        migrations.RenameIndex(
            model_name='usersession',
            new_name='api_userses_firebas_a294de_idx',
            old_name='api_userses_firebas_idx',
        ),
    ]
